### ISSUE TITLE
Failed to bulk read. Samsung galaxy a20e.

### ISSUE THREAD

**Issue by Dv5n** [Samsung-Loki/Thor#15]
## Description
I want to root my phone. (Samsung galaxy a20e) but i keep getting this error (Failed to bulk read: Connection timed out (110).
I just want to install TWRP (Team Win Recovery Project).

## Reproduction
1. Attempt to flash "TWRP.tar"
2. I get the error (Failed to bulk read: Connection timed out (110)

## Photo of the device
No error on device.

## Full logs of the tool, in debug mode
```
Welcome to Thor Shell v1.0.4!
Successfully loaded "usb.ids" from cache.
Type "help" for list of commands.
To start off, type "connect" to initiate a connection.
~~~~~~~~ Platform specific notes ~~~~~~~~
You have to run Thor as root or edit udev rules as follows:
1) create and open /etc/udev/rules.d/51-android.rules in an editor
2) enter SUBSYSTEM=="usb", ATTR{idVendor}=="04e8", MODE="0666", GROUP="YourUserGroupHere"
Additionally, you may have to disable the cdc_acm kernel module:
1) To temporarily unload, run "sudo modprobe -r cdc_acm"
2) To disable it, run "echo 'blacklist cdc_acm' | sudo tee -a /etc/modprobe.d/cdc_acm-blacklist.conf"
shell> debug on
Enabled debug logging
shell> connect
[16:23:09 DBG] Number of configurations: 1
[16:23:09 DBG] Number of interfaces: 2
[16:23:09 DBG] ~~~~ Interface index 0 ~~~~
[16:23:09 DBG] Number of endpoints: 1
[16:23:09 DBG] Interface class: 0x02
[16:23:09 DBG] $$ Endpoint index 0 $$
[16:23:09 DBG] !! Class-dependant descriptor, skipping (len = 5 - 2)
[16:23:09 DBG] !! Class-dependant descriptor, skipping (len = 5 - 2)
[16:23:09 DBG] !! Class-dependant descriptor, skipping (len = 4 - 2)
[16:23:09 DBG] !! Class-dependant descriptor, skipping (len = 5 - 2)
[16:23:09 DBG] Endpoint address: 0x83
[16:23:09 DBG] !! USB_ENDPOINT_XFER_BULK fail (value = 03)
[16:23:09 DBG] !! Interface is invalid, continuing
[16:23:09 DBG] ~~~~ Interface index 1 ~~~~
[16:23:09 DBG] Number of endpoints: 2
[16:23:09 DBG] Interface class: 0x0A
[16:23:09 DBG] $$ Endpoint index 0 $$
[16:23:09 DBG] Endpoint address: 0x81
[16:23:09 DBG] $$ Endpoint index 1 $$
[16:23:09 DBG] Endpoint address: 0x02
[16:23:09 DBG] > Interface is valid, exiting
[16:23:09 DBG] Interface: 0x01, Alternate: 0x00, Read Endpoint: 0x81, Write Endpoint: 0x02
Successfully connected to the device!
Now run "begin" with the protocol you need.
shell> begin odin
[16:23:45 DBG] Bootloader version integer 0x00030000
[16:23:45 DBG] Unknown1: 0, Unknown2: 0, Version: 3
[16:23:45 DBG] Sending file part size of 1048576
Successfully began an Odin session!
shell> help
[required] {optional} - option list
<required> (optional) - usual argument
Total commands: 11
exit - Closes the shell, quit also works
disconnect - Closes the current connection
debug [on/off] - enables or disables debug log level
devParse <path> - Parse a /dev/bus/usb file for debug purposes
connect - Initializes a connection
read <amount> - Spits out raw bytes from the device
begin [odin] - Begins a session with chosen protocol
end - Ends the current protocol session and shuts the device down if possible
Total protocol commands: 11
printPit (filename) - Prints PIT in human readable form, can pull it from device directly
write [string/int/bytes] <content> - Send a packet of specified type, aligns to odin packet size
flashFile <size> - Permanently erases a partition, you have to supply it's size in bytes
factoryReset - Erases the userdata partition, will take a while
setRegion <code> - Changes the region code of the device
flashFile <filename> - Flash a file onto the device
flashTar <directory> - Flashes odin .tar.md5 or .tar files in a directory (AP, BL, CP, CSC)
printPit <filename> - Prints PIT contents in human readable form
options [tflash/efsclear/blupdate/resetfc] (true/false) - Sets an Odin flash option, can show you current value
dumpPit <filename> - Dumps device's PIT to a file
reboot [odin/normal] - Reboots the device
shell> flashTar /F
[16:24:28 DBG] Full exception: System.ApplicationException: Failed to bulk read: Connection timed out (110)
   at TheAirBlow.Thor.Library.Platform.Linux.Interop.HandleError(String message) in /home/theairblow/RiderProjects/Thor/TheAirBlow.Thor.Library/Platform/Linux.cs:line 366
   at TheAirBlow.Thor.Library.Platform.Linux.BulkRead(Int32 amount, Int32& read, Int32 timeout) in /home/theairblow/RiderProjects/Thor/TheAirBlow.Thor.Library/Platform/Linux.cs:line 228
   at TheAirBlow.Thor.Library.Protocols.Odin.DumpPIT() in /home/theairblow/RiderProjects/Thor/TheAirBlow.Thor.Library/Protocols/Odin.cs:line 205
   at ThorRewrite.Shell.Commands.ProtoOdin.FlashTar.RunCommand(State state, List`1 args) in /home/theairblow/RiderProjects/Thor/TheAirBlow.Thor.Shell/Commands/ProtoOdin/FlashTar.cs:line 22
~~~~~~~^
Failed to bulk read: Connection timed out (110)
shell> sad
```

## Hardware and software
 - OS of the computer used: [Linux Mint]
 - Model of the device: [SM-A202F]

## Additional context
I think is something to do with the device. I'm not sure.
I have all of the files (BL AP CP CSC).
I run this tool as root.
The bootloader on the phone is unlocked.
And it is in download mode. And it says, stuff at the top.

**Comment by maeehart** [comment]
I have this exact problem with Samsung Note 9 (Exynos). I am running Arch Linux.

**Comment by enescetinkal** [comment]
same here with a debian pc trying to flash twrp to a j7 prime.

**Comment by ethical-haquer** [comment]
> same here with a debian pc trying to flash twrp to a j7 prime.

Hopefully this bug will be fixed at some point. In the meantime, try using [Odin4](https://xdaforums.com/t/official-samsung-odin-v4-1-2-1-dc05e3ea-for-linux.4453423/).

**Comment by Dv5n** [comment]
(Did with another PC)
I no longer want a rooted phone,
I rooted it (kinda) (just installed TWRP), and I was ready to root it, I looked in the main (/sdcard) directory, and EVERYTHING was corrupted, it din't even boot (boot loop) and after that I installed the stock that comes on Samsung.
