### ISSUE TITLE
"Failed to find valid endpoints!" issue

### ISSUE THREAD

**Issue by sandeshworld** [Samsung-Loki/Thor#9]
## Description
I can see that Thor is detecting the usb device but when I select the samsung device I get the error:

![image](https://github.com/Samsung-Loki/Thor/assets/28467603/63cbd0d5-02b7-4f19-b84e-a4208553b895)

## Reproduction
1) ./TheAirBlow.Thor.Shell/bin/Debug/net7.0/TheAirBlow.Thor.Shell
2) connect
3) Select the samsung device (it is in ODIN mode - albeit with a BOOT Load Fail error)

## Expected behaviour
I expected it to connect. I also followed the steps:
"~~~~~~~~ Platform specific notes ~~~~~~~~
You have to run Thor as root or edit udev rules as follows:
1) create and open /etc/udev/rules.d/51-android.rules in an editor
2) enter SUBSYSTEM=="usb", ATTR{idVendor}=="04e8", MODE="0666", GROUP="YourUserGroupHere"
Additionally, you may have to disable the cdc_acm kernel module:
1) To temporarily unload, run "sudo modprobe -r cdc_acm"
2) To disable it, run "echo 'blacklist cdc_acm' | sudo tee -a /etc/modprobe.d/cdc_acm-blacklist.conf""
just in case.

## Hardware and software
Host: Ubuntu22.04, amd64
Device: Samsung Nav Tab Active3

dotnet --list-runtimes
Microsoft.AspNetCore.App 7.0.9 [/usr/lib/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.NETCore.App 7.0.9 [/usr/lib/dotnet/shared/Microsoft.NETCore.App]

dotnet --list-sdks
7.0.109 [/usr/lib/dotnet/sdk]

## Additional context
The ODIN desktop app is able to connect fine...

**Comment by TheAirBlow** [comment]
You should have made a protocol bug report... Anyway, do the same thing but with `debug on` beforehand.

**Comment by sandeshworld** [comment]
Great. Will try that. Thank you

**Comment by Bluexin** [comment]
Hello.
I am facing the same issue, using SMT725 (Galaxy tab s5e)
Here is the debug output as requested :
```
[20:12:27 DBG] Number of configurations: 1
[20:12:27 DBG] Number of interfaces: 2
[20:12:27 DBG] ~~~~ Interface index 0 ~~~~
[20:12:27 DBG] Number of endpoints: 1
[20:12:27 DBG] Interface class: 0x02
[20:12:27 DBG] $$ Endpoint index 0 $$
[20:12:27 DBG] !! Class-dependant descriptor, skipping (len = 6 - 2)
[20:12:27 DBG] !! Class-dependant descriptor, skipping (len = 5 - 2)
[20:12:27 DBG] !! Class-dependant descriptor, skipping (len = 4 - 2)
[20:12:27 DBG] !! Class-dependant descriptor, skipping (len = 5 - 2)
[20:12:27 DBG] Endpoint address: 0x82
[20:12:27 DBG] !! USB_ENDPOINT_XFER_BULK fail (value = 03)
[20:12:27 DBG] !! Interface is invalid, continuing
[20:12:27 DBG] ~~~~ Interface index 1 ~~~~
[20:12:27 DBG] !! USB_DT_INTERFACE fail (value = 30)
[20:12:27 DBG] Number of endpoints: 0
[20:12:27 DBG] Interface class: 0x00
[20:12:27 DBG] !! Interface is invalid, continuing
[20:12:27 DBG] Full exception: System.InvalidOperationException: Failed to find valid endpoints!
   at TheAirBlow.Thor.Library.Platform.Linux.Initialize(String id, Byte[] direct) in /home/theairblow/RiderProjects/Thor/TheAirBlow.Thor.Library/Platform/Linux.cs:line 144
   at ThorRewrite.Shell.Commands.Connect.RunCommand(State state, List`1 args) in /home/theairblow/RiderProjects/Thor/TheAirBlow.Thor.Shell/Commands/Connect.cs:line 26
~~~~~~~^
Failed to find valid endpoints!
```
(also, I'm surprised to see the debug info isn't relative to project root...)

**Comment by TheAirBlow** [comment]
> Hello. I am facing the same issue, using SMT725 (Galaxy tab s5e) Note that I am running Thor as root. Here is the debug output as requested :
> 
> ```
> [20:12:27 DBG] Number of configurations: 1
> [20:12:27 DBG] Number of interfaces: 2
> [20:12:27 DBG] ~~~~ Interface index 0 ~~~~
> [20:12:27 DBG] Number of endpoints: 1
> [20:12:27 DBG] Interface class: 0x02
> [20:12:27 DBG] $$ Endpoint index 0 $$
> [20:12:27 DBG] !! Class-dependant descriptor, skipping (len = 6 - 2)
> [20:12:27 DBG] !! Class-dependant descriptor, skipping (len = 5 - 2)
> [20:12:27 DBG] !! Class-dependant descriptor, skipping (len = 4 - 2)
> [20:12:27 DBG] !! Class-dependant descriptor, skipping (len = 5 - 2)
> [20:12:27 DBG] Endpoint address: 0x82
> [20:12:27 DBG] !! USB_ENDPOINT_XFER_BULK fail (value = 03)
> [20:12:27 DBG] !! Interface is invalid, continuing
> [20:12:27 DBG] ~~~~ Interface index 1 ~~~~
> [20:12:27 DBG] !! USB_DT_INTERFACE fail (value = 30)
> [20:12:27 DBG] Number of endpoints: 0
> [20:12:27 DBG] Interface class: 0x00
> [20:12:27 DBG] !! Interface is invalid, continuing
> [20:12:27 DBG] Full exception: System.InvalidOperationException: Failed to find valid endpoints!
>    at TheAirBlow.Thor.Library.Platform.Linux.Initialize(String id, Byte[] direct) in /home/theairblow/RiderProjects/Thor/TheAirBlow.Thor.Library/Platform/Linux.cs:line 144
>    at ThorRewrite.Shell.Commands.Connect.RunCommand(State state, List`1 args) in /home/theairblow/RiderProjects/Thor/TheAirBlow.Thor.Shell/Commands/Connect.cs:line 26
> ~~~~~~~^
> Failed to find valid endpoints!
> ```
> 
> (also, I'm surprised to see the debug info isn't relative to project root...)

It's probably `cdc_acm` interfering, Thor tells you what to do to get rid of it.
If that doesn't help, send the `/dev/bus/usb/AAA/BBB` file. To get AAA and BBB, do the following:
1) Connect the device in download mode to your computer and run `lsusb`
2) Find the line with your Samsung phone, and here's `Bus AAA Device BBB`

**Comment by undefynedd** [comment]
Hey, same issue. I haven't done anything related to Samsung with my Linux machine before, but I followed all the steps on Arch Linux and got this:
```
[17:14:08 DBG] Number of configurations: 1
[17:14:08 DBG] Number of interfaces: 3
[17:14:08 DBG] ~~~~ Interface index 0 ~~~~
[17:14:08 DBG] Number of endpoints: 3
[17:14:08 DBG] Interface class: 0x06
[17:14:08 DBG] $$ Endpoint index 0 $$
[17:14:08 DBG] Endpoint address: 0x81
[17:14:08 DBG] $$ Endpoint index 1 $$
[17:14:08 DBG] Endpoint address: 0x01
[17:14:08 DBG] $$ Endpoint index 2 $$
[17:14:08 DBG] Endpoint address: 0x82
[17:14:08 DBG] !! USB_ENDPOINT_XFER_BULK fail (value = 03)
[17:14:08 DBG] !! Interface is invalid, continuing
[17:14:08 DBG] ~~~~ Interface index 1 ~~~~
[17:14:08 DBG] !! USB_DT_INTERFACE fail (value = 0B)
[17:14:08 DBG] Number of endpoints: 2
[17:14:08 DBG] Interface class: 0x02
[17:14:08 DBG] $$ Endpoint index 0 $$
[17:14:08 DBG] !! USB_DT_ENDPOINT fail (value = 01)
[17:14:08 DBG] Endpoint address: 0x00
[17:14:08 DBG] !! USB_ENDPOINT_XFER_BULK fail (value = 01)
[17:14:08 DBG] $$ Endpoint index 1 $$
[17:14:08 DBG] Endpoint address: 0x24
[17:14:08 DBG] !! USB_ENDPOINT_XFER_BULK fail (value = 00)
[17:14:08 DBG] !! Interface is invalid, continuing
[17:14:08 DBG] ~~~~ Interface index 2 ~~~~
[17:14:08 DBG] !! USB_DT_INTERFACE fail (value = 01)
[17:14:08 DBG] Number of endpoints: 4
[17:14:08 DBG] Interface class: 0x24
[17:14:08 DBG] $$ Endpoint index 0 $$
[17:14:08 DBG] !! USB_DT_ENDPOINT fail (value = 06)
[17:14:08 DBG] Endpoint address: 0x01
[17:14:08 DBG] $$ Endpoint index 1 $$
[17:14:08 DBG] !! USB_DT_ENDPOINT fail (value = 0A)
[17:14:08 DBG] Endpoint address: 0x00
[17:14:08 DBG] !! USB_ENDPOINT_XFER_BULK fail (value = 09)
[17:14:08 DBG] $$ Endpoint index 2 $$
[17:14:08 DBG] !! USB_DT_ENDPOINT fail (value = 02)
[17:14:08 DBG] Endpoint address: 0x0A
[17:14:08 DBG] !! USB_ENDPOINT_XFER_BULK fail (value = 00)
[17:14:08 DBG] $$ Endpoint index 3 $$
[17:14:08 DBG] !! USB_DT_ENDPOINT fail (value = 83)
[17:14:08 DBG] Endpoint address: 0x02
[17:14:08 DBG] !! USB_ENDPOINT_XFER_BULK fail (value = 00)
[17:14:08 DBG] !! Interface is invalid, continuing
[17:14:08 DBG] Full exception: System.InvalidOperationException: Failed to find valid endpoints!
   at TheAirBlow.Thor.Library.Platform.Linux.Initialize(String id, Byte[] direct) in /home/<...>/Thor/TheAirBlow.Thor.Library/Platform/Linux.cs:line 144
   at TheAirBlow.Thor.Shell.Commands.Connect.RunCommand(State state, List`1 args) in /home/<...>/Thor/TheAirBlow.Thor.Shell/Commands/Connect.cs:line 26
~~~~~~~^
Failed to find valid endpoints!
```

**Comment by TheAirBlow** [comment]
Run `lsusb` with the device connected, you'll get something like this:
```
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 001 Device 002: ID 3277:0029 Shine-optics USB2.0 HD UVC WebCam
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 003 Device 002: ID 1532:00b2 Razer USA, Ltd Razer DeathAdder V3
Bus 003 Device 003: ID 8087:0032 Intel Corp. AX210 Bluetooth
Bus 004 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 005 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 006 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 007 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 008 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 009 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 010 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
```

Then upload the file called `/dev/bus/usb/BUS/DEV`, where BUS and DEV correspond to `Bus BUS Device DEV` of your Samsung device

**Comment by thefiredragon** [comment]
Try to use an USB-A to USB-C cable, this resolves it for me.

**Comment by andria-dev** [comment]
Was just running into this same issue on v1.1.0.

```
Welcome to Thor Shell v1.1.0!
Successfully loaded "usb.ids" from cache.
Type "help" for list of commands.
To start off, type "connect" to initiate a connection.
~~~~~~~~ Platform specific notes ~~~~~~~~
You have to run Thor as root or edit udev rules as follows:
1) create and open /etc/udev/rules.d/51-android.rules in an editor
2) enter SUBSYSTEM=="usb", ATTR{idVendor}=="04e8", MODE="0666", GROUP="YourUserGroupHere"
Additionally, you may have to disable the cdc_acm kernel module:
1) To temporarily unload, run "sudo modprobe -r cdc_acm"
2) To disable it, run "echo 'blacklist cdc_acm' | sudo tee -a /etc/modprobe.d/cdc_acm-blacklist.conf"
shell> debug on
Enabled debug logging
shell> connect
[09:33:23 DBG] Number of configurations: 1
[09:33:23 DBG] Number of interfaces: 2
[09:33:23 DBG] ~~~~ Interface index 0 ~~~~
[09:33:23 DBG] Number of endpoints: 1
[09:33:23 DBG] Interface class: 0x02
[09:33:23 DBG] $$ Endpoint index 0 $$
[09:33:23 DBG] !! Class-dependant descriptor, skipping (len = 6 - 2)
[09:33:23 DBG] !! Class-dependant descriptor, skipping (len = 5 - 2)
[09:33:23 DBG] !! Class-dependant descriptor, skipping (len = 4 - 2)
[09:33:23 DBG] !! Class-dependant descriptor, skipping (len = 5 - 2)
[09:33:23 DBG] Endpoint address: 0x82
[09:33:23 DBG] !! USB_ENDPOINT_XFER_BULK fail (value = 03)
[09:33:23 DBG] !! Interface is invalid, continuing
[09:33:23 DBG] ~~~~ Interface index 1 ~~~~
[09:33:23 DBG] !! USB_DT_INTERFACE fail (value = 30)
[09:33:23 DBG] Number of endpoints: 0
[09:33:23 DBG] Interface class: 0x00
[09:33:23 DBG] !! Interface is invalid, continuing
[09:33:23 DBG] Full exception: System.InvalidOperationException: Failed to find valid endpoints!
   at TheAirBlow.Thor.Library.Platform.Linux.Initialize(String, Byte[]) + 0x92a
   at TheAirBlow.Thor.Shell.Commands.Connect.RunCommand(State, List`1) + 0x1b3
~~~~~~~^
Failed to find valid endpoints!

```

[device.bin.zip](https://github.com/user-attachments/files/24941674/device.bin.zip)

I used a USB A-to-C cable, ran `modprobe -r cdc_acm` as root beforehand, and ran Thor as root as well. Still no luck though.

**Comment by DutchessNicole** [comment]
Same issue for me. I have a Samsung A7 tablet (minimum spec) that also does not show any valid endpoints.

```
root@FrostyNicole:~# lsusb | grep -i Samsung
Bus 003 Device 005: ID 04e8:6860 Samsung Electronics Co., Ltd Galaxy series, misc. (MTP mode)
root@FrostyNicole:~# cat /dev/bus/usb/003/005 > samsung-a7
```
The above created file was attached to this post.

the ACM module was already disabled before I tried this:
```
root@FrostyNicole:~# lsmod | grep acm
root@FrostyNicole:~# 
```

Below the information the tool gives me:
```
|-- nicole@FrostyNicole:~/Downloads/thor-samsung --|
$ sudo ./Thor-Linux 
[sudo] password for nicole:         
Welcome to Thor Shell v1.1.0!
Successfully loaded "usb.ids" from cache.
Type "help" for list of commands.
To start off, type "connect" to initiate a connection.
~~~~~~~~ Platform specific notes ~~~~~~~~
You have to run Thor as root or edit udev rules as follows:
1) create and open /etc/udev/rules.d/51-android.rules in an editor
2) enter SUBSYSTEM=="usb", ATTR{idVendor}=="04e8", MODE="0666", GROUP="YourUserGroupHere"
Additionally, you may have to disable the cdc_acm kernel module:
1) To temporarily unload, run "sudo modprobe -r cdc_acm"
2) To disable it, run "echo 'blacklist cdc_acm' | sudo tee -a /etc/modprobe.d/cdc_acm-blacklist.conf"
shell> connec 
~~~~~~~^
This command does not exist
shell> connect
~~~~~~~^
Failed to find valid endpoints!
shell> help
Note: beginning a protocol session unlocks new commands for you to use
Note: they can also override the default commands for extension purposes
[required] {optional} - option list
<required> (optional) - usual argument
Total commands: 11
exit - Closes the shell, quit also works
disconnect - Closes the current connection
printPit <filename> - Prints PIT contents in human readable form
debug [on/off] - enables or disables debug log level
devParse <path> - Parse a /dev/bus/usb file for debug purposes
connect - Initializes a connection
write [string/int/bytes] <content> - Send a packet of specified type
read <amount> - Spits out raw bytes from the device
begin [odin] - Begins a session with chosen protocol
end - Ends the current protocol session and shuts the device down if possible
shell> debug on  
Enabled debug logging
shell> connect
[18:47:20 DBG] Number of configurations: 1
[18:47:20 DBG] Number of interfaces: 4
[18:47:20 DBG] ~~~~ Interface index 0 ~~~~
[18:47:20 DBG] Number of endpoints: 3
[18:47:20 DBG] Interface class: 0x06
[18:47:20 DBG] $$ Endpoint index 0 $$
[18:47:20 DBG] Endpoint address: 0x81
[18:47:20 DBG] $$ Endpoint index 1 $$
[18:47:20 DBG] Endpoint address: 0x01
[18:47:20 DBG] $$ Endpoint index 2 $$
[18:47:20 DBG] Endpoint address: 0x82
[18:47:20 DBG] !! USB_ENDPOINT_XFER_BULK fail (value = 03)
[18:47:20 DBG] !! Interface is invalid, continuing
[18:47:20 DBG] ~~~~ Interface index 1 ~~~~
[18:47:20 DBG] !! USB_DT_INTERFACE fail (value = 0B)
[18:47:20 DBG] Number of endpoints: 2
[18:47:20 DBG] Interface class: 0x02
[18:47:20 DBG] $$ Endpoint index 0 $$
[18:47:20 DBG] !! USB_DT_ENDPOINT fail (value = 01)
[18:47:20 DBG] Endpoint address: 0x00
[18:47:20 DBG] !! USB_ENDPOINT_XFER_BULK fail (value = 01)
[18:47:20 DBG] $$ Endpoint index 1 $$
[18:47:20 DBG] Endpoint address: 0x24
[18:47:20 DBG] !! USB_ENDPOINT_XFER_BULK fail (value = 00)
[18:47:20 DBG] !! Interface is invalid, continuing
[18:47:20 DBG] ~~~~ Interface index 2 ~~~~
[18:47:20 DBG] !! USB_DT_INTERFACE fail (value = 01)
[18:47:20 DBG] Number of endpoints: 4
[18:47:20 DBG] Interface class: 0x24
[18:47:20 DBG] $$ Endpoint index 0 $$
[18:47:20 DBG] !! USB_DT_ENDPOINT fail (value = 06)
[18:47:20 DBG] Endpoint address: 0x01
[18:47:20 DBG] $$ Endpoint index 1 $$
[18:47:20 DBG] !! USB_DT_ENDPOINT fail (value = 0A)
[18:47:20 DBG] Endpoint address: 0x00
[18:47:20 DBG] !! USB_ENDPOINT_XFER_BULK fail (value = 09)
[18:47:20 DBG] $$ Endpoint index 2 $$
[18:47:20 DBG] !! USB_DT_ENDPOINT fail (value = 02)
[18:47:20 DBG] Endpoint address: 0x0A
[18:47:20 DBG] !! USB_ENDPOINT_XFER_BULK fail (value = 00)
[18:47:20 DBG] $$ Endpoint index 3 $$
[18:47:20 DBG] !! USB_DT_ENDPOINT fail (value = 83)
[18:47:20 DBG] Endpoint address: 0x02
[18:47:20 DBG] !! USB_ENDPOINT_XFER_BULK fail (value = 00)
[18:47:20 DBG] !! Interface is invalid, continuing
[18:47:20 DBG] ~~~~ Interface index 3 ~~~~
[18:47:20 DBG] !! USB_DT_INTERFACE fail (value = 02)
[18:47:20 DBG] Number of endpoints: 2
[18:47:20 DBG] Interface class: 0x00
[18:47:20 DBG] $$ Endpoint index 0 $$
[18:47:20 DBG] !! USB_DT_ENDPOINT fail (value = 02)
[18:47:20 DBG] Endpoint address: 0xFF
[18:47:20 DBG] $$ Endpoint index 1 $$
[18:47:20 DBG] !! USB_DT_ENDPOINT fail (value = 03)
[18:47:20 DBG] Endpoint address: 0x02
[18:47:20 DBG] !! USB_ENDPOINT_XFER_BULK fail (value = 00)
[18:47:20 DBG] !! Interface is invalid, continuing
[18:47:20 DBG] Full exception: System.InvalidOperationException: Failed to find valid endpoints!
   at TheAirBlow.Thor.Library.Platform.Linux.Initialize(String, Byte[]) + 0x92a
   at TheAirBlow.Thor.Shell.Commands.Connect.RunCommand(State, List`1) + 0x1b3
~~~~~~~^
Failed to find valid endpoints!

```
